format = """
$username\
$directory\
$git_branch\
$git_status\
$git_metrics\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
$character
"""
right_format = """
$time\
$cmd_duration\
$memory_usage
"""

[memory_usage]
disabled = true 
threshold = -1
symbol = ' '
format = 'mem: [${ram_pct}( | ${swap})]($style) '
style = 'bold dimmed green'


[git_metrics]
only_nonzero_diffs = true
disabled = false
 
[character]
success_symbol = "[ insert❯](purple)"
error_symbol = "[ insert❯](red)"
vimcmd_symbol = "[ normal❮](green)"
# Disable the blank line at the start of the prompt
# add_newline = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = "[  ](green)"
disabled = false
show_always = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
format = "[  ](green)"

[directory]
format = "[ $path ](green)"
truncation_length = 3

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
format = '[ $symbol ](cyan)'

[docker_context]
symbol = " "
format = '[ $symbol $context ](cyan) $path'

[elixir]
symbol = " "
format = '[ $symbol ](cyan)'

[elm]
symbol = " "
format = '[ $symbol ](cyan)'

[git_branch]
symbol = ""
format = '[ $symbol $branch ](cyan)'

[git_status]
format = '[$all_status$ahead_behind ](cyan)'

[golang]
symbol = " "
format = '[ $symbol ](cyan)'

[gradle]
format = '[ $symbol ](cyan)'

[haskell]
symbol = " "
format = '[ $symbol ](cyan)'

[java]
symbol = " "
format = '[ $symbol ](cyan)'

[julia]
symbol = " "
format = '[ $symbol ](cyan)'

[nodejs]
symbol = ""
format = '[ $symbol ](#BB9B03)'

[nim]
symbol = "󰆥 "
format = '[ $symbol ](cyan)'

[rust]
symbol = ""
format = '[ $symbol ](#df6022)'

[scala]
symbol = " "
format = '[ $symbol ](cyan)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ $time ](cyan)'
