require("plugins.packer")
-- require("plugins.config.alpha")
require("plugins.config.bufferline")
require("plugins.config.catppuccin")
require("plugins.config.cellular-automation")
require("plugins.config.lualine")
require("plugins.config.nvim-tree")
require("plugins.config.telescope")
require("plugins.config.lsp-zero")
-- require("plugins.config.tokyonight")
require("plugins.config.treesitter")
require("plugins.config.undotree")
require("plugins.config.copy")
require("plugins.config.mason")
